stages:
  - build

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Xmx4096m -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true"
  DOCKET_HOST: "unix:///private/var/tmp/docker.sock" #"tcp://localhost:2375"

Validate:
  image: cschockaert/docker-npm-maven:latest
  stage: build
  tags: 
    - dind
  script:
    - mvn $MAVEN_CLI_OPTS clean install 
    - cd 04.BackendRTE
    - mvn $MAVEN_CLI_OPTS clean install 
    - cd ../03.FrontendRTE
    - mvn generate-sources -U
    - mvn clean install
