<#-- (c) https://github.com/MontiCore/monticore -->
<#--
  Contains the copyright of the generated files as Java-Comment
  
  @params    mc.ast.ASTNode  $ast
  @result    mc.ast.Comment
-->
${tc.signature("dateHelper")}
// This file is generated by MontiCore/UMLP, Dex-Tool Version 1.0
// generated at ${dateHelper.getTime()?datetime} from ${ast.class}
// This file is under AFL copyright <#-- TODO: Clarify licence! --> 
// see also: http://www.monticore.de 
