package de.montigem.be.system.sensor.dtos;

import de.montigem.be.authz.util.SecurityHelper;
import de.montigem.be.domain.cdmodelhwc.classes.sensor.Sensor;
import de.montigem.be.domain.cdmodelhwc.classes.sensortype.SensorType;
import de.montigem.be.domain.cdmodelhwc.classes.sensorvalue.SensorValue;
import de.montigem.be.util.DAOLib;

import java.util.List;

/**
 * DTOLoader for the HeatmapChart (using motion sensor data)
 * The class overwrites the default DTOLoader automatically generated by the MontiGem framework
 */
public class MotionSensorDataDTOLoader extends MotionSensorDataDTOLoaderTOP {

    public MotionSensorDataDTOLoader() {
        super();
    }

    /**
     * Transforms the required data into a DTO for the coresponding chart
     */
    public MotionSensorDataDTOLoader(DAOLib daoLib, SecurityHelper securityHelper) {
        MotionSensorDataDTO dto = new MotionSensorDataDTO();
        List<Sensor> sensors = daoLib.getSensorDAO().getListOfSensorsForType(securityHelper.getSessionCompliantResource(), SensorType.MOTION);
        sensors.forEach((sensor) -> {
            List<SensorValue> entryValues = sensor.getValues();
            entryValues.forEach((entryValue)->{
                MotionSensorEntryDTO entryDTO = new MotionSensorEntryDTO();
                entryDTO.setTimestamp((int) entryValue.getTimestamp().toEpochSecond());
                entryDTO.setName(sensor.getSensorId());
                entryDTO.setId(entryValue.getId());
                dto.getEntries().add(entryDTO);
            });
        });
        setDTO(dto);

    }

    public MotionSensorDataDTOLoader(DAOLib daoLib, long id, SecurityHelper securityHelper) {
        super(daoLib, id, securityHelper);
    }
}